#ifndef _RFB_RFBCONFIG_H
#define _RFB_RFBCONFIG_H 1

/* rfb/rfbconfig.h - Generated for Android/AOSP build */

/* Enable 24 bit per pixel in native framebuffer */
#define LIBVNCSERVER_ALLOW24BPP 1

/* Standard POSIX functions available on Android */
#define LIBVNCSERVER_HAVE_DIRENT_H 1
#define LIBVNCSERVER_HAVE_ENDIAN_H 1
#define LIBVNCSERVER_HAVE_FCNTL_H 1
#define LIBVNCSERVER_HAVE_GETTIMEOFDAY 1
#define LIBVNCSERVER_HAVE_GETHOSTBYNAME 1
#define LIBVNCSERVER_HAVE_GETHOSTNAME 1
#define LIBVNCSERVER_HAVE_INET_NTOA 1
#define LIBVNCSERVER_HAVE_MEMMOVE 1
#define LIBVNCSERVER_HAVE_MEMSET 1
#define LIBVNCSERVER_HAVE_MKFIFO 1
#define LIBVNCSERVER_HAVE_SELECT 1
#define LIBVNCSERVER_HAVE_SOCKET 1
#define LIBVNCSERVER_HAVE_STRCHR 1
#define LIBVNCSERVER_HAVE_STRCSPN 1
#define LIBVNCSERVER_HAVE_STRDUP 1
#define LIBVNCSERVER_HAVE_STRERROR 1
#define LIBVNCSERVER_HAVE_STRSTR 1
#define LIBVNCSERVER_HAVE_NETINET_IN_H 1
#define LIBVNCSERVER_HAVE_SYS_SOCKET_H 1
#define LIBVNCSERVER_HAVE_SYS_STAT_H 1
#define LIBVNCSERVER_HAVE_SYS_TIME_H 1
#define LIBVNCSERVER_HAVE_SYS_TYPES_H 1
#define LIBVNCSERVER_HAVE_SYS_WAIT_H 1
#define LIBVNCSERVER_HAVE_SYS_UIO_H 1
#define LIBVNCSERVER_HAVE_SYS_RESOURCE_H 1
#define LIBVNCSERVER_HAVE_UNISTD_H 1
#define LIBVNCSERVER_HAVE_VPRINTF 1
#define LIBVNCSERVER_HAVE_FORK 1
#define LIBVNCSERVER_HAVE_WORKING_FORK 1
#define LIBVNCSERVER_HAVE_MMAP 1

/* Libraries enabled */
#define LIBVNCSERVER_HAVE_LIBJPEG 1
#define LIBVNCSERVER_HAVE_LIBZ 1
#define LIBVNCSERVER_HAVE_LIBPTHREAD 1

/* IPv6 support */
#define LIBVNCSERVER_IPv6 1

/* Package info */
#define LIBVNCSERVER_PACKAGE_STRING "LibVNCServer 0.9.15"
#define LIBVNCSERVER_PACKAGE_VERSION "0.9.15"
#define LIBVNCSERVER_VERSION "0.9.15"
#define LIBVNCSERVER_VERSION_MAJOR "0"
#define LIBVNCSERVER_VERSION_MINOR "9"
#define LIBVNCSERVER_VERSION_PATCHLEVEL "15"

/* Types */
#define HAVE_LIBVNCSERVER_PID_T 1
#define HAVE_LIBVNCSERVER_SIZE_T 1
#define HAVE_LIBVNCSERVER_SOCKLEN_T 1

#endif /* _RFB_RFBCONFIG_H */
